# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: video_analyzer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'video_analyzer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14video_analyzer.proto\x12\x0evideo_analyzer\"N\n\x0cVideoRequest\x12\x12\n\nvideo_data\x18\x01 \x01(\x0c\x12\x12\n\nvideo_name\x18\x02 \x01(\t\x12\x16\n\x0e\x61nalysis_types\x18\x03 \x03(\t\"W\n\x0e\x41nalysisUpdate\x12\r\n\x05stage\x18\x01 \x01(\t\x12\x10\n\x08progress\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x13\n\x0bresult_json\x18\x04 \x01(\t\"4\n\rReportRequest\x12\x13\n\x0b\x61nalysis_id\x18\x01 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\"7\n\x0eReportResponse\x12\x13\n\x0breport_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"K\n\x0b\x43hatMessage\x12\r\n\x05query\x18\x01 \x01(\t\x12\x17\n\x0f\x63onversation_id\x18\x02 \x01(\t\x12\x14\n\x0c\x63ontext_json\x18\x03 \x01(\t\"P\n\x0c\x43hatResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\x11\n\tdata_json\x18\x04 \x01(\t\"5\n\x1a\x43onversationHistoryRequest\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\"4\n\x1b\x43onversationHistoryResponse\x12\x15\n\rmessages_json\x18\x01 \x01(\t2\xf1\x02\n\rVideoAnalyzer\x12N\n\x0c\x41nalyzeVideo\x12\x1c.video_analyzer.VideoRequest\x1a\x1e.video_analyzer.AnalysisUpdate0\x01\x12O\n\x0eGenerateReport\x12\x1d.video_analyzer.ReportRequest\x1a\x1e.video_analyzer.ReportResponse\x12L\n\x0fSendChatMessage\x12\x1b.video_analyzer.ChatMessage\x1a\x1c.video_analyzer.ChatResponse\x12q\n\x16GetConversationHistory\x12*.video_analyzer.ConversationHistoryRequest\x1a+.video_analyzer.ConversationHistoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_analyzer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEOREQUEST']._serialized_start=40
  _globals['_VIDEOREQUEST']._serialized_end=118
  _globals['_ANALYSISUPDATE']._serialized_start=120
  _globals['_ANALYSISUPDATE']._serialized_end=207
  _globals['_REPORTREQUEST']._serialized_start=209
  _globals['_REPORTREQUEST']._serialized_end=261
  _globals['_REPORTRESPONSE']._serialized_start=263
  _globals['_REPORTRESPONSE']._serialized_end=318
  _globals['_CHATMESSAGE']._serialized_start=320
  _globals['_CHATMESSAGE']._serialized_end=395
  _globals['_CHATRESPONSE']._serialized_start=397
  _globals['_CHATRESPONSE']._serialized_end=477
  _globals['_CONVERSATIONHISTORYREQUEST']._serialized_start=479
  _globals['_CONVERSATIONHISTORYREQUEST']._serialized_end=532
  _globals['_CONVERSATIONHISTORYRESPONSE']._serialized_start=534
  _globals['_CONVERSATIONHISTORYRESPONSE']._serialized_end=586
  _globals['_VIDEOANALYZER']._serialized_start=589
  _globals['_VIDEOANALYZER']._serialized_end=958
# @@protoc_insertion_point(module_scope)
