# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import video_analyzer_pb2 as video__analyzer__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in video_analyzer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VideoAnalyzerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeVideo = channel.unary_stream(
                '/video_analyzer.VideoAnalyzer/AnalyzeVideo',
                request_serializer=video__analyzer__pb2.VideoRequest.SerializeToString,
                response_deserializer=video__analyzer__pb2.AnalysisUpdate.FromString,
                _registered_method=True)
        self.GenerateReport = channel.unary_unary(
                '/video_analyzer.VideoAnalyzer/GenerateReport',
                request_serializer=video__analyzer__pb2.ReportRequest.SerializeToString,
                response_deserializer=video__analyzer__pb2.ReportResponse.FromString,
                _registered_method=True)
        self.SendChatMessage = channel.unary_unary(
                '/video_analyzer.VideoAnalyzer/SendChatMessage',
                request_serializer=video__analyzer__pb2.ChatMessage.SerializeToString,
                response_deserializer=video__analyzer__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.GetConversationHistory = channel.unary_unary(
                '/video_analyzer.VideoAnalyzer/GetConversationHistory',
                request_serializer=video__analyzer__pb2.ConversationHistoryRequest.SerializeToString,
                response_deserializer=video__analyzer__pb2.ConversationHistoryResponse.FromString,
                _registered_method=True)


class VideoAnalyzerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeVideo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendChatMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConversationHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoAnalyzerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeVideo': grpc.unary_stream_rpc_method_handler(
                    servicer.AnalyzeVideo,
                    request_deserializer=video__analyzer__pb2.VideoRequest.FromString,
                    response_serializer=video__analyzer__pb2.AnalysisUpdate.SerializeToString,
            ),
            'GenerateReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateReport,
                    request_deserializer=video__analyzer__pb2.ReportRequest.FromString,
                    response_serializer=video__analyzer__pb2.ReportResponse.SerializeToString,
            ),
            'SendChatMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendChatMessage,
                    request_deserializer=video__analyzer__pb2.ChatMessage.FromString,
                    response_serializer=video__analyzer__pb2.ChatResponse.SerializeToString,
            ),
            'GetConversationHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConversationHistory,
                    request_deserializer=video__analyzer__pb2.ConversationHistoryRequest.FromString,
                    response_serializer=video__analyzer__pb2.ConversationHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'video_analyzer.VideoAnalyzer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('video_analyzer.VideoAnalyzer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VideoAnalyzer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/video_analyzer.VideoAnalyzer/AnalyzeVideo',
            video__analyzer__pb2.VideoRequest.SerializeToString,
            video__analyzer__pb2.AnalysisUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/video_analyzer.VideoAnalyzer/GenerateReport',
            video__analyzer__pb2.ReportRequest.SerializeToString,
            video__analyzer__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendChatMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/video_analyzer.VideoAnalyzer/SendChatMessage',
            video__analyzer__pb2.ChatMessage.SerializeToString,
            video__analyzer__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConversationHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/video_analyzer.VideoAnalyzer/GetConversationHistory',
            video__analyzer__pb2.ConversationHistoryRequest.SerializeToString,
            video__analyzer__pb2.ConversationHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
